# Generated by Django 4.1.2 on 2023-11-27 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntelReport',
            fields=[
                ('ir_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ir_reporter_name', models.CharField(max_length=255)),
                ('ir_reporting_time', models.DateTimeField()),
                ('ir_jetty', models.CharField(max_length=255)),
                ('ir_total_boats', models.IntegerField()),
                ('ir_pf_id', models.CharField(max_length=100)),
                ('ir_rdt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'intel_report',
            },
        ),
        migrations.CreateModel(
            name='IntelReportDetails',
            fields=[
                ('ird_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ird_boat_types', models.CharField(max_length=255)),
                ('ird_total_boats', models.IntegerField()),
                ('ird_detected_from', models.DateTimeField()),
                ('ird_detected_to', models.DateTimeField()),
                ('ird_act_observed', models.TextField()),
                ('ird_transferring_loc', models.CharField(max_length=255)),
                ('ird_probability', models.FloatField()),
                ('ird_boat_picture', models.ImageField(upload_to='boat_images/')),
                ('ird_nakwa_name', models.CharField(max_length=255)),
                ('ird_number_of_crew', models.IntegerField()),
                ('ird_owner_name', models.CharField(max_length=255)),
                ('report', models.ForeignKey(db_column='report', on_delete=django.db.models.deletion.CASCADE, related_name='irdetails', to='intel.intelreport')),
            ],
            options={
                'db_table': 'intel_report_details',
            },
        ),
    ]
