# Generated by Django 4.1.2 on 2023-11-28 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intelreport',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='intelreportdetails',
            options={'managed': False},
        ),
    ]
