# Generated by Django 4.1.2 on 2023-09-28 09:14

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('u_pf_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fdensity',
            fields=[
                ('fd_key', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('no_vessels', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fdensity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grdensity',
            fields=[
                ('grd_key', models.AutoField(primary_key=True, serialize=False)),
                ('grd_position', models.TextField()),
                ('grd_qty', models.SmallIntegerField()),
                ('grd_type', models.CharField(max_length=100)),
                ('grd_movement', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'grdensity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Greports',
            fields=[
                ('gr_key', models.AutoField(primary_key=True, serialize=False)),
                ('gr_pf_id', models.CharField(max_length=100)),
                ('gr_dtg', models.DateTimeField()),
                ('gr_position', models.TextField()),
                ('gr_patroltype', models.CharField(blank=True, max_length=100, null=True)),
                ('gr_fuelrem', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('gr_info', models.CharField(blank=True, max_length=100, null=True)),
                ('gr_rdt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'greports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grfishing',
            fields=[
                ('grf_key', models.AutoField(primary_key=True, serialize=False)),
                ('grf_position', models.TextField()),
                ('grf_name', models.CharField(max_length=100)),
                ('grf_type', models.CharField(max_length=100)),
                ('grf_movement', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'grfishing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grmerchant',
            fields=[
                ('grm_key', models.AutoField(primary_key=True, serialize=False)),
                ('grm_position', models.TextField()),
                ('grm_name', models.CharField(max_length=100)),
                ('grm_type', models.CharField(max_length=100)),
                ('grm_movement', models.CharField(max_length=100)),
                ('grm_lpoc', models.CharField(blank=True, max_length=100, null=True)),
                ('grm_npoc', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'grmerchant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Narco',
            fields=[
                ('n_key', models.IntegerField(primary_key=True, serialize=False)),
                ('dtg', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('value', models.BigIntegerField(blank=True, null=True)),
                ('flag', models.CharField(blank=True, max_length=50, null=True)),
                ('item', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('vessel_name', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'narco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Platforms',
            fields=[
                ('pf_key', models.AutoField(primary_key=True, serialize=False)),
                ('pf_id', models.CharField(max_length=100, unique=True)),
                ('pf_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('pf_type', models.CharField(blank=True, max_length=100, null=True)),
                ('pf_squadron', models.CharField(blank=True, max_length=100, null=True)),
                ('pf_co', models.CharField(blank=True, max_length=100, null=True)),
                ('pf_info', models.CharField(blank=True, max_length=100, null=True)),
                ('pf_rdt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'platforms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rvcrews',
            fields=[
                ('rvc_key', models.AutoField(primary_key=True, serialize=False)),
                ('rvc_name', models.CharField(max_length=100)),
                ('rvc_id', models.CharField(max_length=100)),
                ('rvc_idtype', models.CharField(blank=True, max_length=100, null=True)),
                ('rvc_idexpdt', models.DateField(blank=True, null=True)),
                ('rvc_nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('rvc_ethnicity', models.CharField(blank=True, max_length=100, null=True)),
                ('rvc_type', models.CharField(blank=True, max_length=100, null=True)),
                ('rvc_cell', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'rvcrews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rvessels',
            fields=[
                ('rv_key', models.AutoField(primary_key=True, serialize=False)),
                ('rv_id', models.CharField(max_length=100)),
                ('rv_name', models.CharField(max_length=100)),
                ('rv_regno', models.CharField(max_length=100)),
                ('rv_type', models.CharField(max_length=100)),
                ('rv_flag', models.CharField(max_length=100)),
                ('rv_province', models.CharField(blank=True, max_length=100, null=True)),
                ('rv_length', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('rv_breadth', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('rv_tonnage', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('rv_crew', models.SmallIntegerField(blank=True, null=True)),
                ('rv_pf_id', models.CharField(blank=True, max_length=100, null=True)),
                ('rv_rdt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rvessels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rvowners',
            fields=[
                ('rvo_key', models.AutoField(primary_key=True, serialize=False)),
                ('rvo_type', models.CharField(max_length=100)),
                ('rvo_name', models.CharField(max_length=100)),
                ('rvo_id', models.CharField(blank=True, max_length=100, null=True)),
                ('rvo_idtype', models.CharField(blank=True, max_length=100, null=True)),
                ('rvo_idexpdt', models.DateField(blank=True, null=True)),
                ('rvo_nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('rvo_ethnicity', models.CharField(blank=True, max_length=100, null=True)),
                ('rvo_share', models.SmallIntegerField(blank=True, null=True)),
                ('rvo_cell', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'rvowners',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpatialRefSys',
            fields=[
                ('srid', models.IntegerField(primary_key=True, serialize=False)),
                ('auth_name', models.CharField(blank=True, max_length=256, null=True)),
                ('auth_srid', models.IntegerField(blank=True, null=True)),
                ('srtext', models.CharField(blank=True, max_length=2048, null=True)),
                ('proj4text', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'db_table': 'spatial_ref_sys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Srcrews',
            fields=[
                ('src_key', models.AutoField(primary_key=True, serialize=False)),
                ('src_srv_key', models.IntegerField()),
                ('src_name', models.CharField(max_length=100)),
                ('src_id', models.CharField(blank=True, max_length=100, null=True)),
                ('src_idtype', models.CharField(blank=True, max_length=100, null=True)),
                ('src_idexpdt', models.DateField(blank=True, null=True)),
                ('src_nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('src_ethnicity', models.CharField(blank=True, max_length=100, null=True)),
                ('src_type', models.CharField(blank=True, max_length=100, null=True)),
                ('src_cell', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'srcrews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sreports',
            fields=[
                ('sr_key', models.AutoField(primary_key=True, serialize=False)),
                ('sr_pf_id', models.CharField(max_length=100)),
                ('sr_dtg', models.DateTimeField()),
                ('sr_position', models.TextField()),
                ('sr_rv_key', models.IntegerField()),
                ('sr_type', models.CharField(blank=True, max_length=100, null=True)),
                ('sr_movement', models.CharField(blank=True, max_length=100, null=True)),
                ('sr_action', models.CharField(blank=True, max_length=100, null=True)),
                ('sr_info', models.CharField(blank=True, max_length=100, null=True)),
                ('sr_rdt', models.DateTimeField(blank=True, null=True)),
                ('sr_fuelrem', models.IntegerField()),
                ('sr_patroltype', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'sreports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Srgoods',
            fields=[
                ('srg_key', models.AutoField(primary_key=True, serialize=False)),
                ('srg_item', models.CharField(blank=True, max_length=100, null=True)),
                ('srg_qty', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('srg_denomination', models.CharField(blank=True, max_length=100, null=True)),
                ('srg_category', models.CharField(blank=True, max_length=100, null=True)),
                ('srg_subcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('srg_value', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('srg_source', models.CharField(blank=True, max_length=100, null=True)),
                ('srg_confiscated', models.BooleanField()),
                ('srg_remarks', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'srgoods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Srowners',
            fields=[
                ('sro_key', models.AutoField(primary_key=True, serialize=False)),
                ('sro_srv_key', models.IntegerField()),
                ('sro_type', models.CharField(max_length=100)),
                ('sro_name', models.CharField(max_length=100)),
                ('sro_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sro_idtype', models.CharField(blank=True, max_length=100, null=True)),
                ('sro_idexpdt', models.DateField(blank=True, null=True)),
                ('sro_nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('sro_ethnicity', models.CharField(blank=True, max_length=100, null=True)),
                ('sro_share', models.SmallIntegerField(blank=True, null=True)),
                ('sro_cell', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'srowners',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reg_no', models.CharField(blank=True, max_length=50, null=True)),
                ('reg_date', models.DateField(blank=True, null=True)),
                ('boat_name', models.CharField(blank=True, max_length=50, null=True)),
                ('boat_type', models.CharField(blank=True, max_length=50, null=True)),
                ('boat_location', models.CharField(blank=True, max_length=50, null=True)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('pc_date', models.DateField(blank=True, null=True)),
                ('arrival_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sreports1',
            fields=[
                ('sr_key', models.OneToOneField(db_column='sr1_key', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='fishing_trip', serialize=False, to='msa.sreports')),
                ('sr_depjetty', models.CharField(blank=True, max_length=100, null=True)),
                ('sr_depdt', models.DateField(blank=True, null=True)),
                ('sr_pc', models.CharField(blank=True, max_length=100, null=True)),
                ('sr_pcissuedt', models.DateField(blank=True, null=True)),
                ('sr_pcdays', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sreports1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sreports2',
            fields=[
                ('sr_key', models.OneToOneField(db_column='sr2_key', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='merchant_trip', serialize=False, to='msa.sreports')),
                ('sr2_lpoc', models.CharField(blank=True, max_length=100, null=True)),
                ('sr2_lpocdtg', models.DateField(blank=True, null=True)),
                ('sr2_npoc', models.CharField(blank=True, max_length=100, null=True)),
                ('sr2_npoceta', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sreports2',
                'managed': False,
            },
        ),
    ]
