# Generated by Django 4.2.5 on 2023-12-28 07:18

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("ais", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pnscshipdata",
            options={"managed": False},
        ),
        migrations.CreateModel(
            name="ShipBreaking",
            fields=[
                ("sb_key", models.BigAutoField(primary_key=True, serialize=False)),
                ("sb_dtg", models.DateTimeField(blank=True, null=True)),
                ("sb_flag_reg_cert", models.BooleanField()),
                ("sb_crew", models.IntegerField(blank=True, null=True)),
                ("sb_imo_verified", models.BooleanField()),
                ("sb_agreement_memo", models.BooleanField()),
                ("sc_credit_let", models.BooleanField()),
                ("sb_lpoc", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "sb_mast_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "sb_mast_nationality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "sb_buyer_comp_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "sb_buyer_comp_num",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "sb_owner_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "sb_owner_num",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "sb_locshipping_comp_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "sb_locshipping_agent_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "sb_locshipping_agent_num",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("sb_sec_team", models.BooleanField()),
                ("sb_haz_material", models.BooleanField()),
                ("sb_gas_free_cert", models.BooleanField()),
                ("sb_waste_free_cert", models.BooleanField()),
                ("sb_import_gen_manifest", models.BooleanField()),
                (
                    "sb_comm_equip_list",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        size=None,
                    ),
                ),
                ("sb_goods_dec_doc", models.BooleanField()),
                ("sb_del_cert", models.BooleanField()),
                ("sb_iso_cert", models.BooleanField()),
                ("sb_ex_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "sb_emb_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("sb_rdt", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "sb_mv_key",
                    models.ForeignKey(
                        db_column="sb_mv_key",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ais.merchant_vessel",
                    ),
                ),
            ],
            options={
                "db_table": "ship_breaking",
            },
        ),
        migrations.CreateModel(
            name="Sbcrews",
            fields=[
                ("sbc_key", models.BigAutoField(primary_key=True, serialize=False)),
                ("sbc_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "sbc_nationality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "sbc_sb_key",
                    models.ForeignKey(
                        db_column="sbc_sb_key",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sb_crews",
                        to="ais.shipbreaking",
                    ),
                ),
            ],
            options={
                "db_table": "sb_crew",
            },
        ),
    ]
