# Generated by Django 4.1.2 on 2024-01-02 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ais', '0002_alter_pnscshipdata_options_shipbreaking_sbcrews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sbcrews',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='shipbreaking',
            options={'managed': False},
        ),
    ]
