# Generated by Django 4.1.2 on 2024-01-02 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ais', '0003_alter_sbcrews_options_alter_shipbreaking_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='situationalreport',
            options={},
        ),
    ]
